version: '3.7'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    command: bash -c "/wait-for-it.sh --timeout=0 mysql:${MYSQL_PORT}" && uvicorn main:app --reload
    container_name: python-ab_api
    depends_on: [mysql]
    networks:
      - python-ab-network
    ports:
      - "${API_PORT}:8000"
    restart: 'no'
    volumes:
      - ./api/src:/var/src/app

  mysql:
    command: --default-authentication-plugin=mysql_native_password
    container_name: python-ab_mysql
    env_file: ./dev.env
    image: mysql:8.0.23
    networks:
      - python-ab-network
    restart: 'no'

  adminer:
    container_name: python-ab_adminer
    image: adminer
    restart: always
    networks:
      - python-ab-network
    ports:
      - ${ADMINER_PORT}:8080
    restart: 'no'

networks:
  python-ab-network:
    name: python-ab-network
