FROM ubuntu:20.04

WORKDIR /

# Existing lsb_release causes issues with modern installations of Python3
# https://github.com/pypa/pip/issues/4924#issuecomment-435825490
# Set (temporarily) DEBIAN_FRONTEND to avoid interacting with tzdata
RUN apt -qq -y update && \
    DEBIAN_FRONTEND=noninteractive apt-get -qq -y install \
        curl \
        python3 \
        python3-pip

RUN curl -L 'https://raw.githubusercontent.com/marcusnjones/wait-for-it/master/wait-for-it.sh' > ./wait-for-it.sh

RUN chmod +x ./wait-for-it.sh

WORKDIR /var/src/app

CMD [ "tail", "-f", "/dev/null" ]
