FROM ubuntu:21.04

WORKDIR /

RUN apt-get -y update

RUN apt install -y curl

RUN curl -L 'https://raw.githubusercontent.com/marcusnjones/wait-for-it/master/wait-for-it.sh' > ./wait-for-it.sh

RUN chmod +x ./wait-for-it.sh

WORKDIR /var/src/app

RUN tail -f /var/log/*
